[{"topic":"name","detail":"population","caller":"orderly2::outpack_packet_start","log_level":"info","time":1692126582.09757},{"topic":"id","detail":"20230815-190942-11e14cda","caller":"orderly2::outpack_packet_start","log_level":"info","time":1692126582.09824},{"topic":"parameter","detail":["iso: NGA"],"caller":"orderly2::outpack_packet_start","log_level":"info","time":1692126582.0989},{"topic":"start","detail":"2023-08-15 20:09:42","caller":"orderly2::outpack_packet_start","log_level":"info","time":1692126582.09962},{"topic":"result","detail":"failure","caller":"orderly2::orderly_run","log_level":"info","time":1692127078.04305},{"topic":"warning","detail":["\u001b[38;5;101mDetected an unexpected many-to-many relationship between `x` and\n`y`.\n\u001b[36mℹ\u001b[38;5;101m Row 10039 of `x` matches multiple rows in `y`.\n\u001b[36mℹ\u001b[38;5;101m Row 1 of `y` matches multiple rows in `x`.\n\u001b[36mℹ\u001b[38;5;101m If a many-to-many relationship is expected, set `relationship =\n  \"many-to-many\"` to silence this warning.\u001b[39m"],"caller":"orderly2::orderly_run","log_level":"info","time":1692127078.11022},{"topic":"error","detail":"could not find function \"add_units\"","caller":"orderly2::orderly_run","log_level":"info","time":1692127078.11471},{"topic":"trace","detail":["     ▆","  1. ├─rlang::try_fetch(...)","  2. │ ├─base::tryCatch(...)","  3. │ │ └─base (local) tryCatchList(expr, classes, parentenv, handlers)","  4. │ │   └─base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])","  5. │ │     └─base (local) doTryCatch(return(expr), name, parentenv, handler)","  6. │ └─base::withCallingHandlers(...)","  7. ├─withr::with_dir(path, source_echo(\"orderly.R\", envir, p$logger$console))","  8. │ └─base::force(code)","  9. ├─orderly2:::source_echo(\"orderly.R\", envir, p$logger$console)"," 10. │ └─base::source(...)"," 11. │   ├─base::withVisible(eval(ei, envir))"," 12. │   └─base::eval(ei, envir)"," 13. │     └─base::eval(ei, envir)"," 14. └─base::.handleSimpleError(...) at orderly.R:71:0"," 15.   └─rlang (local) h(simpleError(msg, call))"," 16.     └─handlers[[2L]](cnd)"],"caller":"orderly2::orderly_run","log_level":"info","time":1692127078.14124},{"topic":"end","detail":"2023-08-15 20:17:58","caller":"orderly2::outpack_packet_end","log_level":"info","time":1692127078.55886},{"topic":"elapsed","detail":"8.274356 mins","caller":"orderly2::outpack_packet_end","log_level":"info","time":1692127078.55963}]
